TOPLEVEL_LANG = verilog

VERILOG_SOURCES = $(PWD)/pipeline_adder_128bit.v

TOPLEVEL = pipeline_adder_128bit

MODULE = test_pipeline_adder

SIM = verilator

include $(shell cocotb-config --makefiles)/Makefile.sim
