TOPLEVEL_LANG = verilog

VERILOG_SOURCES = $(PWD)/pipeline_multiplier_8bit.v

TOPLEVEL = pipeline_multiplier_8bit

MODULE = test_pipeline_multiplier

SIM = verilator

include $(shell cocotb-config --makefiles)/Makefile.sim
